{% set name = "pytest-split" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 446f330e3607572027f3861058c27d9b3eaa80d83dc86675abe2978bbf50c02f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - setuptools-scm
    - poetry
    - pip
  run:
    - python >=3.6,<4
    - pytest >=5.4

test:
  requires:
    - pip
  commands:
    - pip check
    - pytest --traceconfig | grep pytest-split-{{ version }}

about:
  home: https://github.com/jerry-git/pytest-split
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: pytest plugin to split tests based on execution time.
  description: pytest plugin which splits the test suite to equally sized "sub suites" based on test execution time.

  doc_url: https://github.com/jerry-git/pytest-split
  dev_url: https://github.com/jerry-git/pytest-split

extra:
  recipe-maintainers:
    - maresb
    - ma-sadeghi
