{% set name = "pytest-split" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67a8a7a56891202390808e3642a242cd146cfbf0fe42f205ea9bfc0f748e7c98

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - setuptools-scm
    - poetry
    - pip
  run:
    - python >=3.6,<4
    - pytest >=5.4

test:
  requires:
    - pip
  commands:
    - pip check
    - pytest --traceconfig | grep pytest-split-{{ version }}

about:
  home: https://github.com/jerry-git/pytest-split
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: pytest plugin to split tests based on execution time.
  description: pytest plugin which splits the test suite to equally sized "sub suites" based on test execution time.

  doc_url: https://github.com/jerry-git/pytest-split
  dev_url: https://github.com/jerry-git/pytest-split

extra:
  recipe-maintainers:
    - ma-sadeghi
