{% set name = "pytest-split" %}
{% set version = "0.10.0" %}
{% set python_min = python_min|default("0.1a0") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_split-{{ version }}.tar.gz
  sha256: adf80ba9fef7be89500d571e705b4f963dfa05038edf35e4925817e6b34ea66f

build:
  entry_points:
    - slowest-tests = pytest_split.cli:list_slowest_tests
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=5.0.0,<9.0.0

test:
  imports:
    - pytest_split
  commands:
    - pip check
    - slowest-tests --help
    - pytest --traceconfig | grep pytest-split-{{ version }}
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/jerry-git/pytest-split
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest plugin to split tests based on execution time.
  description: Pytest plugin which splits the test suite to equally sized sub suites based on test execution time.

  doc_url: https://jerry-git.github.io/pytest-split
  dev_url: https://github.com/jerry-git/pytest-split

extra:
  recipe-maintainers:
    - maresb
    - ma-sadeghi
